### PR TITLE
Fixed `rectx template add <template>` error message recognising non-existent files

### LINKED ISSUE #63: `rectx template add` will not recognise a non-existent file (responding error assumes file exists?)
**Describe the issue**
When running `rectx template add <file>` if the file does not exist, `rectx` will respond with an error about the file not being a `.rectx.template`. Additional logic need to be added so it checks if the file exists and if not a better error message is sent.

**Screenshots**
File "x" does not exist, but the error message *assumes* it exists.
image

### PR DESCRIPTION
**Pull request by hrszpuk**
## Fixes
- Removed file existence checks in `main.go`
- Added file existence checks in function `AddTemplate` in package `config/template.go`
- Added `utilities.Check` error messaging instead of printing then exiting
- Also fixed typos in error messages in function `AddTemplate`

## Related Issues/PR
- Close #63

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -53,13 +53,7 @@ func main() {
...
 		case "add":
 			EnsureArguments(4, "template add")
-			// TODO Maybe check if file exists first?
-			if !strings.HasSuffix(os.Args[3], ".rectx.template") {
-				fmt.Printf("Whoops \"%s\" isn't a .rectx.template file!\n", os.Args[3])
-				os.Exit(1)
-			} else {
-				config.AddTemplate(os.Args[3])
-			}
+			config.AddTemplate(os.Args[3])
```
Comment (hrszpuk) [inline main.go:56]: NOTE: this check is now handled by `AddTemplate` instead of `Main`.

**Review by hrszpuk — COMMENTED** [review]
LGTM
